name: time_app
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: '>=2.17.0-44.1.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.1
  http: ^0.13.0
  flutter_spinkit: ^5.0.0
  font_awesome_flutter: ^10.6.0
  fluttertoast: ^8.2.4
  intl: ^0.18.1
  firebase_core: ^2.16.0
  firebase_auth: ^4.10.0
  cloud_firestore: ^4.9.2
  table_calendar: ^3.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.0.15
  cloud_firestore: ^4.13.2

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/

  fonts:
    - family: Spartan MB
      fonts:
        - asset: lib/assets/fonts/SpartanMB-Black.otf
          weight: 900
